depot/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelingFood</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyzvNDff7DcvGP8W61amXY8oIwNBzwFLI&libraries=places&callback=initMap" async defer>
    </script>
            
    <script>
      
      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: 21.15611, lng: -100.9325};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 3000,
          type: ['restaurant']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
          toggleBounce();
        });
          
       function toggleBounce() {
        if (marker.getAnimation() !== null) {
          marker.setAnimation(null);
        } else {
          marker.setAnimation(google.maps.Animation.BOUNCE);
        }
      }
      }
    </script>
      
  </head>
  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.to_s), onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>
        <%= image_tag 'logoTravelingFood', alt: 'TravekingFood' %>
      <span class="title"><%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        <div id="cart">
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>
        </div>

        <ul>
          <li><a href="http://www...."><%= t('.Inicio') %></a></li>
            <li><%= link_to "Ordenes", orders_path%></li>
          <li><a href="http://www..../news"><%= t('.Noticias') %></a></li>
          <li><a href='http://www..../contact'><%= t('.Contacto') %></a></li>
        </ul>
      </div>

      <% if session[:user_id] %>
        <ul>
            <li><%= link_to 'Ordenes', orders_path %></li>
            <li><%= link_to 'Productos', products_path %></li>
          <li><%= link_to 'Usuarios', users_path %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
      <div id="main">
        <%= yield %>
          <div id="map"></div>
        
      </div>
      </div>
    </div>
  </body>
</html>
 <!--Galeria de comida dolorence API AIzaSyC5z87QigtMXQJjCW9cX2245_hpDBCVRyA, AIzaSyCyzvNDff7DcvGP8W61amXY8oIwNBzwFLI
lat: 21.15611, lng: -100.9325-->